name: e2e suite 2

on:
  push:
    branches:
      - master
      - development
      - release
  pull_request:

jobs:
  e2e_test:
    runs-on: ubuntu-18.04
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0-amd64
        ports:
          - 9200/tcp
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
      mongodb:
        image: mongo:4.2.6
        ports:
          - 27017/tcp
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.6.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.6.x'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn install
      - run: sudo apt update
      - run: sudo apt-get install poppler-utils
      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: ./prod
          key: >-
            ${{ runner.os }}-build-${{ hashFiles('app/**/*.*') }}-
            ${{ hashFiles('database/**/*.*') }}-
            ${{ hashFiles('**/yarn.lock') }}-
            ${{ hashFiles('**/webpack.production.config.js') }}-
            ${{ hashFiles('**/.babelrc') }}-
            ${{ hashFiles('webpack/**/config.js') }}-
      - name: build production
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: yarn production-build
      - run: yarn blank-state
        env:
          DBHOST: localhost:${{ job.services.mongodb.ports[27017] }}
          ELASTICSEARCH_URL: http://localhost:${{ job.services.elasticsearch.ports[9200] }}
      - name: start Uwazi
        env:
          DBHOST: localhost:${{ job.services.mongodb.ports[27017] }}
          ELASTICSEARCH_URL: http://localhost:${{ job.services.elasticsearch.ports[9200] }}
        run: yarn run-production &
      - name: wait for uwazi to be ready
        run: sleep 20 && wget --waitretry=5 --retry-connrefused -v http://localhost:3000/
        timeout-minutes: 5
      - run: xvfb-run -a yarn e2e suite2
        timeout-minutes: 25
        env:
          DBHOST: localhost:${{ job.services.mongodb.ports[27017] }}
          ELASTICSEARCH_URL: http://localhost:${{ job.services.elasticsearch.ports[9200] }}
