name: check-types

on:
  push:
    branches:
      - master
      - development
      - release
  pull_request:

jobs:
  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.6.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.6.x'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn install
      - run: yarn check-types
